services:
  app:
    image: node:20-alpine
    user: node
    volumes:
      - ./:/app
    working_dir: /app
    command: ['npm', 'start']
    environment:
      NODE_ENV: development
      PORT: 8080
    ports:
      - 8080:8080/tcp